# Prometheus global config
global:
  # Tầm suất thu thập metrics
  scrape_interval: 20s # default = 1m
  # Tầm suất đánh giá alert rules
  evaluation_interval: 15s # default = 1m
  # Thời gian timeout với metrics chờ lâu
  scrape_timeout: 18s # default = 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alert-manager:9093"]

# Load rules và định kỳ đánh giá dựa trên 'evaluation_interval'.
rule_files:
  - "rules/*.yml"
# - "cisco-rules.yml"
# - "windows-rules.yml"
# - "global-rules.yml"
# - "firewall-rules.yml"
# - "vmware-rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
        labels:
          hostname: Prometheus
          type: monitoring

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alert-manager:9093"]
        labels:
          hostname: Alertmanager
          type: monitoring

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
        labels:
          hostname: Promtail
          type: monitoring

  - job_name: 'winforms_app1'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:1234']
        labels:
          hostname: WinFormsApp1
          type: winforms

  - job_name: 'winforms_app2'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:1235']
        labels:
          hostname: WinFormsApp2
          type: winforms